# Generated by Django 3.2.18 on 2023-04-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
